// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contentwriter/v1/contentwriter.proto

package contentwriter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	v1 "github.com/nlnwa/veidemann-api-go/config/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	RecordNum            int32    `protobuf:"varint,1,opt,name=record_num,json=recordNum,proto3" json:"record_num,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce7e840e1d52975, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetRecordNum() int32 {
	if m != nil {
		return m.RecordNum
	}
	return 0
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WriteRequestMeta struct {
	ExecutionId          string                                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TargetUri            string                                 `protobuf:"bytes,2,opt,name=target_uri,json=targetUri,proto3" json:"target_uri,omitempty"`
	RecordMeta           map[int32]*WriteRequestMeta_RecordMeta `protobuf:"bytes,3,rep,name=record_meta,json=recordMeta,proto3" json:"record_meta,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FetchTimeStamp       *timestamp.Timestamp                   `protobuf:"bytes,4,opt,name=fetch_time_stamp,json=fetchTimeStamp,proto3" json:"fetch_time_stamp,omitempty"`
	IpAddress            string                                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CollectionRef        *v1.ConfigRef                          `protobuf:"bytes,7,opt,name=collection_ref,json=collectionRef,proto3" json:"collection_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *WriteRequestMeta) Reset()         { *m = WriteRequestMeta{} }
func (m *WriteRequestMeta) String() string { return proto.CompactTextString(m) }
func (*WriteRequestMeta) ProtoMessage()    {}
func (*WriteRequestMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce7e840e1d52975, []int{1}
}

func (m *WriteRequestMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequestMeta.Unmarshal(m, b)
}
func (m *WriteRequestMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequestMeta.Marshal(b, m, deterministic)
}
func (m *WriteRequestMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequestMeta.Merge(m, src)
}
func (m *WriteRequestMeta) XXX_Size() int {
	return xxx_messageInfo_WriteRequestMeta.Size(m)
}
func (m *WriteRequestMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequestMeta.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequestMeta proto.InternalMessageInfo

func (m *WriteRequestMeta) GetExecutionId() string {
	if m != nil {
		return m.ExecutionId
	}
	return ""
}

func (m *WriteRequestMeta) GetTargetUri() string {
	if m != nil {
		return m.TargetUri
	}
	return ""
}

func (m *WriteRequestMeta) GetRecordMeta() map[int32]*WriteRequestMeta_RecordMeta {
	if m != nil {
		return m.RecordMeta
	}
	return nil
}

func (m *WriteRequestMeta) GetFetchTimeStamp() *timestamp.Timestamp {
	if m != nil {
		return m.FetchTimeStamp
	}
	return nil
}

func (m *WriteRequestMeta) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *WriteRequestMeta) GetCollectionRef() *v1.ConfigRef {
	if m != nil {
		return m.CollectionRef
	}
	return nil
}

type WriteRequestMeta_RecordMeta struct {
	RecordNum            int32                           `protobuf:"varint,1,opt,name=record_num,json=recordNum,proto3" json:"record_num,omitempty"`
	Type                 RecordType                      `protobuf:"varint,2,opt,name=type,proto3,enum=veidemann.api.contentwriter.v1.RecordType" json:"type,omitempty"`
	RecordContentType    string                          `protobuf:"bytes,3,opt,name=record_content_type,json=recordContentType,proto3" json:"record_content_type,omitempty"`
	BlockDigest          string                          `protobuf:"bytes,4,opt,name=block_digest,json=blockDigest,proto3" json:"block_digest,omitempty"`
	PayloadDigest        string                          `protobuf:"bytes,5,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`
	Size                 int64                           `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	SubCollection        v1.Collection_SubCollectionType `protobuf:"varint,7,opt,name=sub_collection,json=subCollection,proto3,enum=veidemann.api.config.v1.Collection_SubCollectionType" json:"sub_collection,omitempty"`
	WarcConcurrentTo     []string                        `protobuf:"bytes,8,rep,name=warc_concurrent_to,json=warcConcurrentTo,proto3" json:"warc_concurrent_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *WriteRequestMeta_RecordMeta) Reset()         { *m = WriteRequestMeta_RecordMeta{} }
func (m *WriteRequestMeta_RecordMeta) String() string { return proto.CompactTextString(m) }
func (*WriteRequestMeta_RecordMeta) ProtoMessage()    {}
func (*WriteRequestMeta_RecordMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce7e840e1d52975, []int{1, 0}
}

func (m *WriteRequestMeta_RecordMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequestMeta_RecordMeta.Unmarshal(m, b)
}
func (m *WriteRequestMeta_RecordMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequestMeta_RecordMeta.Marshal(b, m, deterministic)
}
func (m *WriteRequestMeta_RecordMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequestMeta_RecordMeta.Merge(m, src)
}
func (m *WriteRequestMeta_RecordMeta) XXX_Size() int {
	return xxx_messageInfo_WriteRequestMeta_RecordMeta.Size(m)
}
func (m *WriteRequestMeta_RecordMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequestMeta_RecordMeta.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequestMeta_RecordMeta proto.InternalMessageInfo

func (m *WriteRequestMeta_RecordMeta) GetRecordNum() int32 {
	if m != nil {
		return m.RecordNum
	}
	return 0
}

func (m *WriteRequestMeta_RecordMeta) GetType() RecordType {
	if m != nil {
		return m.Type
	}
	return RecordType_WARCINFO
}

func (m *WriteRequestMeta_RecordMeta) GetRecordContentType() string {
	if m != nil {
		return m.RecordContentType
	}
	return ""
}

func (m *WriteRequestMeta_RecordMeta) GetBlockDigest() string {
	if m != nil {
		return m.BlockDigest
	}
	return ""
}

func (m *WriteRequestMeta_RecordMeta) GetPayloadDigest() string {
	if m != nil {
		return m.PayloadDigest
	}
	return ""
}

func (m *WriteRequestMeta_RecordMeta) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *WriteRequestMeta_RecordMeta) GetSubCollection() v1.Collection_SubCollectionType {
	if m != nil {
		return m.SubCollection
	}
	return v1.Collection_UNDEFINED
}

func (m *WriteRequestMeta_RecordMeta) GetWarcConcurrentTo() []string {
	if m != nil {
		return m.WarcConcurrentTo
	}
	return nil
}

type WriteRequest struct {
	// Types that are valid to be assigned to Value:
	//	*WriteRequest_Meta
	//	*WriteRequest_ProtocolHeader
	//	*WriteRequest_Payload
	//	*WriteRequest_Cancel
	Value                isWriteRequest_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce7e840e1d52975, []int{2}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

type isWriteRequest_Value interface {
	isWriteRequest_Value()
}

type WriteRequest_Meta struct {
	Meta *WriteRequestMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type WriteRequest_ProtocolHeader struct {
	ProtocolHeader *Data `protobuf:"bytes,2,opt,name=protocol_header,json=protocolHeader,proto3,oneof"`
}

type WriteRequest_Payload struct {
	Payload *Data `protobuf:"bytes,3,opt,name=payload,proto3,oneof"`
}

type WriteRequest_Cancel struct {
	Cancel string `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*WriteRequest_Meta) isWriteRequest_Value() {}

func (*WriteRequest_ProtocolHeader) isWriteRequest_Value() {}

func (*WriteRequest_Payload) isWriteRequest_Value() {}

func (*WriteRequest_Cancel) isWriteRequest_Value() {}

func (m *WriteRequest) GetValue() isWriteRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *WriteRequest) GetMeta() *WriteRequestMeta {
	if x, ok := m.GetValue().(*WriteRequest_Meta); ok {
		return x.Meta
	}
	return nil
}

func (m *WriteRequest) GetProtocolHeader() *Data {
	if x, ok := m.GetValue().(*WriteRequest_ProtocolHeader); ok {
		return x.ProtocolHeader
	}
	return nil
}

func (m *WriteRequest) GetPayload() *Data {
	if x, ok := m.GetValue().(*WriteRequest_Payload); ok {
		return x.Payload
	}
	return nil
}

func (m *WriteRequest) GetCancel() string {
	if x, ok := m.GetValue().(*WriteRequest_Cancel); ok {
		return x.Cancel
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WriteRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WriteRequest_Meta)(nil),
		(*WriteRequest_ProtocolHeader)(nil),
		(*WriteRequest_Payload)(nil),
		(*WriteRequest_Cancel)(nil),
	}
}

type WriteResponseMeta struct {
	RecordMeta           map[int32]*WriteResponseMeta_RecordMeta `protobuf:"bytes,1,rep,name=record_meta,json=recordMeta,proto3" json:"record_meta,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *WriteResponseMeta) Reset()         { *m = WriteResponseMeta{} }
func (m *WriteResponseMeta) String() string { return proto.CompactTextString(m) }
func (*WriteResponseMeta) ProtoMessage()    {}
func (*WriteResponseMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce7e840e1d52975, []int{3}
}

func (m *WriteResponseMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponseMeta.Unmarshal(m, b)
}
func (m *WriteResponseMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponseMeta.Marshal(b, m, deterministic)
}
func (m *WriteResponseMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponseMeta.Merge(m, src)
}
func (m *WriteResponseMeta) XXX_Size() int {
	return xxx_messageInfo_WriteResponseMeta.Size(m)
}
func (m *WriteResponseMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponseMeta.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponseMeta proto.InternalMessageInfo

func (m *WriteResponseMeta) GetRecordMeta() map[int32]*WriteResponseMeta_RecordMeta {
	if m != nil {
		return m.RecordMeta
	}
	return nil
}

type WriteResponseMeta_RecordMeta struct {
	RecordNum     int32      `protobuf:"varint,1,opt,name=record_num,json=recordNum,proto3" json:"record_num,omitempty"`
	Type          RecordType `protobuf:"varint,2,opt,name=type,proto3,enum=veidemann.api.contentwriter.v1.RecordType" json:"type,omitempty"`
	WarcId        string     `protobuf:"bytes,3,opt,name=warc_id,json=warcId,proto3" json:"warc_id,omitempty"`
	StorageRef    string     `protobuf:"bytes,4,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	BlockDigest   string     `protobuf:"bytes,5,opt,name=block_digest,json=blockDigest,proto3" json:"block_digest,omitempty"`
	PayloadDigest string     `protobuf:"bytes,6,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`
	// If the stored record was detected as a revisit, this field contains the id of the revisited record.
	RevisitReferenceId   string   `protobuf:"bytes,7,opt,name=revisit_reference_id,json=revisitReferenceId,proto3" json:"revisit_reference_id,omitempty"`
	CollectionFinalName  string   `protobuf:"bytes,8,opt,name=collection_final_name,json=collectionFinalName,proto3" json:"collection_final_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponseMeta_RecordMeta) Reset()         { *m = WriteResponseMeta_RecordMeta{} }
func (m *WriteResponseMeta_RecordMeta) String() string { return proto.CompactTextString(m) }
func (*WriteResponseMeta_RecordMeta) ProtoMessage()    {}
func (*WriteResponseMeta_RecordMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce7e840e1d52975, []int{3, 0}
}

func (m *WriteResponseMeta_RecordMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponseMeta_RecordMeta.Unmarshal(m, b)
}
func (m *WriteResponseMeta_RecordMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponseMeta_RecordMeta.Marshal(b, m, deterministic)
}
func (m *WriteResponseMeta_RecordMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponseMeta_RecordMeta.Merge(m, src)
}
func (m *WriteResponseMeta_RecordMeta) XXX_Size() int {
	return xxx_messageInfo_WriteResponseMeta_RecordMeta.Size(m)
}
func (m *WriteResponseMeta_RecordMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponseMeta_RecordMeta.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponseMeta_RecordMeta proto.InternalMessageInfo

func (m *WriteResponseMeta_RecordMeta) GetRecordNum() int32 {
	if m != nil {
		return m.RecordNum
	}
	return 0
}

func (m *WriteResponseMeta_RecordMeta) GetType() RecordType {
	if m != nil {
		return m.Type
	}
	return RecordType_WARCINFO
}

func (m *WriteResponseMeta_RecordMeta) GetWarcId() string {
	if m != nil {
		return m.WarcId
	}
	return ""
}

func (m *WriteResponseMeta_RecordMeta) GetStorageRef() string {
	if m != nil {
		return m.StorageRef
	}
	return ""
}

func (m *WriteResponseMeta_RecordMeta) GetBlockDigest() string {
	if m != nil {
		return m.BlockDigest
	}
	return ""
}

func (m *WriteResponseMeta_RecordMeta) GetPayloadDigest() string {
	if m != nil {
		return m.PayloadDigest
	}
	return ""
}

func (m *WriteResponseMeta_RecordMeta) GetRevisitReferenceId() string {
	if m != nil {
		return m.RevisitReferenceId
	}
	return ""
}

func (m *WriteResponseMeta_RecordMeta) GetCollectionFinalName() string {
	if m != nil {
		return m.CollectionFinalName
	}
	return ""
}

type WriteReply struct {
	Meta                 *WriteResponseMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WriteReply) Reset()         { *m = WriteReply{} }
func (m *WriteReply) String() string { return proto.CompactTextString(m) }
func (*WriteReply) ProtoMessage()    {}
func (*WriteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce7e840e1d52975, []int{4}
}

func (m *WriteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteReply.Unmarshal(m, b)
}
func (m *WriteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteReply.Marshal(b, m, deterministic)
}
func (m *WriteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteReply.Merge(m, src)
}
func (m *WriteReply) XXX_Size() int {
	return xxx_messageInfo_WriteReply.Size(m)
}
func (m *WriteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteReply.DiscardUnknown(m)
}

var xxx_messageInfo_WriteReply proto.InternalMessageInfo

func (m *WriteReply) GetMeta() *WriteResponseMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "veidemann.api.contentwriter.v1.Data")
	proto.RegisterType((*WriteRequestMeta)(nil), "veidemann.api.contentwriter.v1.WriteRequestMeta")
	proto.RegisterMapType((map[int32]*WriteRequestMeta_RecordMeta)(nil), "veidemann.api.contentwriter.v1.WriteRequestMeta.RecordMetaEntry")
	proto.RegisterType((*WriteRequestMeta_RecordMeta)(nil), "veidemann.api.contentwriter.v1.WriteRequestMeta.RecordMeta")
	proto.RegisterType((*WriteRequest)(nil), "veidemann.api.contentwriter.v1.WriteRequest")
	proto.RegisterType((*WriteResponseMeta)(nil), "veidemann.api.contentwriter.v1.WriteResponseMeta")
	proto.RegisterMapType((map[int32]*WriteResponseMeta_RecordMeta)(nil), "veidemann.api.contentwriter.v1.WriteResponseMeta.RecordMetaEntry")
	proto.RegisterType((*WriteResponseMeta_RecordMeta)(nil), "veidemann.api.contentwriter.v1.WriteResponseMeta.RecordMeta")
	proto.RegisterType((*WriteReply)(nil), "veidemann.api.contentwriter.v1.WriteReply")
}

func init() {
	proto.RegisterFile("contentwriter/v1/contentwriter.proto", fileDescriptor_fce7e840e1d52975)
}

var fileDescriptor_fce7e840e1d52975 = []byte{
	// 888 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x51, 0x6f, 0x1b, 0x45,
	0x10, 0xce, 0xc5, 0x8e, 0x5d, 0x8f, 0x13, 0x37, 0xdd, 0x16, 0x71, 0x58, 0x82, 0x1a, 0xab, 0x48,
	0x56, 0xd5, 0x9e, 0x1b, 0x23, 0x24, 0xa0, 0x08, 0xa5, 0x49, 0x5a, 0x25, 0x0f, 0x14, 0xd8, 0x04,
	0x21, 0x21, 0xa4, 0xd3, 0xfa, 0x6e, 0xec, 0xac, 0x7a, 0xde, 0x3d, 0xf6, 0xf6, 0x1c, 0x5c, 0x5e,
	0xe1, 0x8d, 0x9f, 0xc6, 0x2b, 0xbf, 0x82, 0x3f, 0x81, 0x76, 0xee, 0x1c, 0xc7, 0x09, 0x4a, 0x1c,
	0x55, 0xe2, 0xed, 0x76, 0x66, 0xbe, 0x99, 0x9d, 0x6f, 0xe7, 0x1b, 0x1d, 0x3c, 0x8a, 0xb4, 0xb2,
	0xa8, 0xec, 0x99, 0x91, 0x16, 0x4d, 0x7f, 0xba, 0xd3, 0x5f, 0x32, 0x04, 0xa9, 0xd1, 0x56, 0xb3,
	0x8f, 0xa6, 0x28, 0x63, 0x9c, 0x08, 0xa5, 0x02, 0x91, 0xca, 0x60, 0x39, 0x64, 0xba, 0xd3, 0xfe,
	0x20, 0xd2, 0x6a, 0x24, 0xc7, 0x0e, 0x6e, 0x30, 0xd3, 0xb9, 0x89, 0x30, 0x2b, 0xa0, 0xed, 0xce,
	0x95, 0x02, 0x97, 0x23, 0x1e, 0x8e, 0xb5, 0x1e, 0x27, 0xd8, 0xa7, 0xd3, 0x30, 0x1f, 0xf5, 0xad,
	0x9c, 0x60, 0x66, 0xc5, 0x24, 0x2d, 0x02, 0xba, 0x5f, 0x40, 0xf5, 0x40, 0x58, 0xc1, 0x3e, 0x04,
	0x30, 0x18, 0x69, 0x13, 0x87, 0x2a, 0x9f, 0xf8, 0x5e, 0xc7, 0xeb, 0x6d, 0xf0, 0x46, 0x61, 0x79,
	0x9d, 0x4f, 0x18, 0x83, 0x6a, 0x2c, 0xac, 0xf0, 0xd7, 0x3b, 0x5e, 0x6f, 0x93, 0xd3, 0x77, 0xf7,
	0x9f, 0x1a, 0x6c, 0xff, 0xe8, 0x2a, 0x73, 0xfc, 0x25, 0xc7, 0xcc, 0x7e, 0x83, 0x56, 0xb0, 0x8f,
	0x61, 0x13, 0x7f, 0xc5, 0x28, 0xb7, 0x52, 0xab, 0x50, 0xc6, 0x94, 0xa9, 0xc1, 0x9b, 0xe7, 0xb6,
	0xa3, 0xd8, 0x95, 0xb2, 0xc2, 0x8c, 0xd1, 0x86, 0xb9, 0x91, 0x94, 0xb1, 0xc1, 0x1b, 0x85, 0xe5,
	0x07, 0x23, 0x99, 0x80, 0x66, 0x79, 0x93, 0x09, 0x5a, 0xe1, 0x57, 0x3a, 0x95, 0x5e, 0x73, 0xb0,
	0x1b, 0x5c, 0xcf, 0x52, 0x70, 0xf9, 0x22, 0x01, 0xa7, 0x1c, 0xee, 0xf3, 0xa5, 0xb2, 0x66, 0xc6,
	0xcb, 0xf6, 0xe8, 0x92, 0x07, 0xb0, 0x3d, 0x42, 0x1b, 0x9d, 0x86, 0x8e, 0x8d, 0x90, 0xe8, 0xf0,
	0xab, 0x1d, 0xaf, 0xd7, 0x1c, 0xb4, 0x83, 0x82, 0xb0, 0x60, 0x4e, 0x58, 0x70, 0x32, 0x27, 0x8c,
	0xb7, 0x08, 0xe3, 0xce, 0xc7, 0xee, 0xec, 0xfa, 0x90, 0x69, 0x28, 0xe2, 0xd8, 0x60, 0x96, 0xf9,
	0x1b, 0x45, 0x1f, 0x32, 0x7d, 0x51, 0x18, 0xd8, 0x11, 0xb4, 0x22, 0x9d, 0x24, 0x18, 0x11, 0x15,
	0x06, 0x47, 0x7e, 0x9d, 0x4a, 0x74, 0xaf, 0xb6, 0x32, 0x92, 0x63, 0xd7, 0xc3, 0x3e, 0x7d, 0x71,
	0x1c, 0xf1, 0xad, 0x05, 0x92, 0xe3, 0xa8, 0xfd, 0x47, 0x05, 0x60, 0xd1, 0xcf, 0x4d, 0x6f, 0xf5,
	0x35, 0x54, 0xed, 0x2c, 0x45, 0x62, 0xb6, 0x35, 0x78, 0x7c, 0x13, 0x73, 0x45, 0xe2, 0x93, 0x59,
	0x8a, 0x9c, 0x70, 0x2c, 0x80, 0xfb, 0x65, 0xfa, 0x32, 0x36, 0xa4, 0x74, 0x15, 0x6a, 0xf0, 0x5e,
	0xe1, 0xda, 0x2f, 0x3c, 0x0e, 0xe5, 0x9e, 0x7c, 0x98, 0xe8, 0xe8, 0x4d, 0x18, 0xcb, 0x31, 0x66,
	0x96, 0x98, 0x6c, 0xf0, 0x26, 0xd9, 0x0e, 0xc8, 0xc4, 0x3e, 0x81, 0x56, 0x2a, 0x66, 0x89, 0x16,
	0xf1, 0x3c, 0xa8, 0xa0, 0x6b, 0xab, 0xb4, 0x96, 0x61, 0x0c, 0xaa, 0x99, 0x7c, 0x8b, 0x7e, 0xad,
	0xe3, 0xf5, 0x2a, 0x9c, 0xbe, 0xd9, 0xcf, 0xd0, 0xca, 0xf2, 0x61, 0xb8, 0x20, 0x84, 0x68, 0x6c,
	0x0d, 0x3e, 0xbb, 0x86, 0xc6, 0x79, 0x68, 0x70, 0x9c, 0x0f, 0x17, 0x27, 0x6a, 0x71, 0x2b, 0xbb,
	0x68, 0x62, 0x4f, 0x80, 0x9d, 0x09, 0x13, 0xb9, 0x4e, 0xa3, 0xdc, 0x18, 0x6a, 0x56, 0xfb, 0x77,
	0x3a, 0x95, 0x5e, 0x83, 0x6f, 0x3b, 0xcf, 0xfe, 0xb9, 0xe3, 0x44, 0xb7, 0xdf, 0xc2, 0xdd, 0x4b,
	0x63, 0xc5, 0xb6, 0xa1, 0xf2, 0x06, 0x67, 0xe5, 0x23, 0xb8, 0x4f, 0xf6, 0x3d, 0x6c, 0x4c, 0x45,
	0x92, 0x17, 0xfc, 0x37, 0x07, 0xcf, 0xdf, 0x61, 0x72, 0x79, 0x91, 0xe9, 0xcb, 0xf5, 0xcf, 0xbd,
	0xee, 0x9f, 0xeb, 0xb0, 0x79, 0x31, 0x94, 0xbd, 0x82, 0x2a, 0x09, 0xc4, 0xa3, 0x32, 0xcf, 0x6e,
	0x5b, 0xe6, 0x70, 0x8d, 0x13, 0x9e, 0x7d, 0x0b, 0x77, 0x69, 0xd8, 0x23, 0x9d, 0x84, 0xa7, 0x28,
	0x62, 0x34, 0xe5, 0xcd, 0x1f, 0xdd, 0x94, 0xd2, 0x2d, 0x8e, 0xc3, 0x35, 0xde, 0x9a, 0xc3, 0x0f,
	0x09, 0xcd, 0x76, 0xa1, 0x5e, 0x3e, 0x2b, 0xcd, 0xcc, 0xea, 0x89, 0xe6, 0x30, 0xe6, 0x43, 0x2d,
	0x12, 0x2a, 0xc2, 0xa4, 0x98, 0xa5, 0xc3, 0x35, 0x5e, 0x9e, 0xf7, 0xea, 0x25, 0xb9, 0xdd, 0xbf,
	0xaa, 0x70, 0xaf, 0x6c, 0x29, 0x4b, 0xb5, 0xca, 0x90, 0x94, 0x31, 0x5c, 0xde, 0x1d, 0x1e, 0xed,
	0x8e, 0x17, 0x2b, 0x52, 0xb3, 0xc8, 0x73, 0xdd, 0xf2, 0x68, 0xff, 0xbd, 0xfe, 0x7f, 0x8a, 0xf1,
	0x7d, 0xa8, 0xd3, 0x80, 0xca, 0xb8, 0x14, 0x60, 0xcd, 0x1d, 0x8f, 0x62, 0xf6, 0x10, 0x9a, 0x99,
	0xd5, 0x46, 0x8c, 0x91, 0x76, 0x4b, 0x21, 0x3a, 0x28, 0x4d, 0x1c, 0x47, 0x57, 0x64, 0xb9, 0xb1,
	0x8a, 0x2c, 0x6b, 0xff, 0x25, 0xcb, 0x67, 0xf0, 0xc0, 0xe0, 0x54, 0x66, 0xd2, 0xba, 0x52, 0x68,
	0x50, 0x45, 0xe8, 0x2e, 0x54, 0xa7, 0x60, 0x56, 0xfa, 0xf8, 0xdc, 0x75, 0x14, 0xb3, 0x01, 0xbc,
	0x77, 0x61, 0xf7, 0x8d, 0xa4, 0x12, 0x49, 0xa8, 0xc4, 0x04, 0xfd, 0x3b, 0x04, 0xb9, 0xbf, 0x70,
	0xbe, 0x72, 0xbe, 0xd7, 0x62, 0x82, 0xed, 0xdf, 0x56, 0x11, 0x17, 0x5f, 0x16, 0xd7, 0x57, 0xef,
	0xf2, 0xb4, 0x17, 0xd5, 0x75, 0x0c, 0x50, 0x86, 0xa6, 0xc9, 0x8c, 0xbd, 0x5c, 0x92, 0xd6, 0xce,
	0xad, 0x8b, 0x14, 0xca, 0x1a, 0x4c, 0x61, 0xab, 0xdc, 0x93, 0x14, 0x61, 0x18, 0xc2, 0x06, 0xa1,
	0xd8, 0x93, 0xdb, 0xa8, 0xb5, 0xfd, 0x78, 0xc5, 0xe8, 0x34, 0x99, 0x75, 0xd7, 0x7a, 0xde, 0xde,
	0xef, 0x1e, 0xf4, 0x94, 0x0e, 0xd4, 0x30, 0x50, 0x4a, 0xdc, 0x80, 0xdd, 0x7b, 0xb0, 0x74, 0xc5,
	0x63, 0x34, 0x53, 0x19, 0xe1, 0x77, 0xde, 0x4f, 0xbb, 0x63, 0x69, 0x4f, 0xf3, 0x61, 0x10, 0xe9,
	0x49, 0x5f, 0x25, 0xea, 0x4c, 0xf4, 0xcf, 0x13, 0x3d, 0x15, 0xa9, 0x7c, 0x3a, 0xd6, 0xfd, 0xcb,
	0x7f, 0x1f, 0xcf, 0x97, 0x0c, 0xc3, 0x1a, 0xed, 0x85, 0x4f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x98, 0x23, 0xfa, 0x49, 0x07, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContentWriterClient is the client API for ContentWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContentWriterClient interface {
	Write(ctx context.Context, opts ...grpc.CallOption) (ContentWriter_WriteClient, error)
}

type contentWriterClient struct {
	cc *grpc.ClientConn
}

func NewContentWriterClient(cc *grpc.ClientConn) ContentWriterClient {
	return &contentWriterClient{cc}
}

func (c *contentWriterClient) Write(ctx context.Context, opts ...grpc.CallOption) (ContentWriter_WriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ContentWriter_serviceDesc.Streams[0], "/veidemann.api.contentwriter.v1.ContentWriter/write", opts...)
	if err != nil {
		return nil, err
	}
	x := &contentWriterWriteClient{stream}
	return x, nil
}

type ContentWriter_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*WriteReply, error)
	grpc.ClientStream
}

type contentWriterWriteClient struct {
	grpc.ClientStream
}

func (x *contentWriterWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *contentWriterWriteClient) CloseAndRecv() (*WriteReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContentWriterServer is the server API for ContentWriter service.
type ContentWriterServer interface {
	Write(ContentWriter_WriteServer) error
}

// UnimplementedContentWriterServer can be embedded to have forward compatible implementations.
type UnimplementedContentWriterServer struct {
}

func (*UnimplementedContentWriterServer) Write(srv ContentWriter_WriteServer) error {
	return status.Errorf(codes.Unimplemented, "method Write not implemented")
}

func RegisterContentWriterServer(s *grpc.Server, srv ContentWriterServer) {
	s.RegisterService(&_ContentWriter_serviceDesc, srv)
}

func _ContentWriter_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContentWriterServer).Write(&contentWriterWriteServer{stream})
}

type ContentWriter_WriteServer interface {
	SendAndClose(*WriteReply) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type contentWriterWriteServer struct {
	grpc.ServerStream
}

func (x *contentWriterWriteServer) SendAndClose(m *WriteReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *contentWriterWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ContentWriter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "veidemann.api.contentwriter.v1.ContentWriter",
	HandlerType: (*ContentWriterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "write",
			Handler:       _ContentWriter_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "contentwriter/v1/contentwriter.proto",
}
