// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventhandler/v1/resources.proto

package eventhandler

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventObject_State int32

const (
	EventObject_NEW    EventObject_State = 0
	EventObject_OPEN   EventObject_State = 1
	EventObject_CLOSED EventObject_State = 2
)

var EventObject_State_name = map[int32]string{
	0: "NEW",
	1: "OPEN",
	2: "CLOSED",
}

var EventObject_State_value = map[string]int32{
	"NEW":    0,
	"OPEN":   1,
	"CLOSED": 2,
}

func (x EventObject_State) String() string {
	return proto.EnumName(EventObject_State_name, int32(x))
}

func (EventObject_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb09a02427acf6d9, []int{0, 0}
}

type EventObject_Severity int32

const (
	EventObject_INFO  EventObject_Severity = 0
	EventObject_WARN  EventObject_Severity = 1
	EventObject_ERROR EventObject_Severity = 2
)

var EventObject_Severity_name = map[int32]string{
	0: "INFO",
	1: "WARN",
	2: "ERROR",
}

var EventObject_Severity_value = map[string]int32{
	"INFO":  0,
	"WARN":  1,
	"ERROR": 2,
}

func (x EventObject_Severity) String() string {
	return proto.EnumName(EventObject_Severity_name, int32(x))
}

func (EventObject_Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb09a02427acf6d9, []int{0, 1}
}

type Activity_ChangeType int32

const (
	Activity_CREATED       Activity_ChangeType = 0
	Activity_VALUE_CHANGED Activity_ChangeType = 1
	Activity_ARRAY_ADD     Activity_ChangeType = 2
	Activity_ARRAY_DEL     Activity_ChangeType = 3
)

var Activity_ChangeType_name = map[int32]string{
	0: "CREATED",
	1: "VALUE_CHANGED",
	2: "ARRAY_ADD",
	3: "ARRAY_DEL",
}

var Activity_ChangeType_value = map[string]int32{
	"CREATED":       0,
	"VALUE_CHANGED": 1,
	"ARRAY_ADD":     2,
	"ARRAY_DEL":     3,
}

func (x Activity_ChangeType) String() string {
	return proto.EnumName(Activity_ChangeType_name, int32(x))
}

func (Activity_ChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb09a02427acf6d9, []int{2, 0}
}

type EventObject struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source               string               `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	State                EventObject_State    `protobuf:"varint,4,opt,name=state,proto3,enum=veidemann.api.eventhandler.v1.EventObject_State" json:"state,omitempty"`
	Assignee             string               `protobuf:"bytes,5,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Data                 []*Data              `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty"`
	Severity             EventObject_Severity `protobuf:"varint,7,opt,name=severity,proto3,enum=veidemann.api.eventhandler.v1.EventObject_Severity" json:"severity,omitempty"`
	Label                []string             `protobuf:"bytes,8,rep,name=label,proto3" json:"label,omitempty"`
	Activity             []*Activity          `protobuf:"bytes,9,rep,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventObject) Reset()         { *m = EventObject{} }
func (m *EventObject) String() string { return proto.CompactTextString(m) }
func (*EventObject) ProtoMessage()    {}
func (*EventObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb09a02427acf6d9, []int{0}
}

func (m *EventObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventObject.Unmarshal(m, b)
}
func (m *EventObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventObject.Marshal(b, m, deterministic)
}
func (m *EventObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventObject.Merge(m, src)
}
func (m *EventObject) XXX_Size() int {
	return xxx_messageInfo_EventObject.Size(m)
}
func (m *EventObject) XXX_DiscardUnknown() {
	xxx_messageInfo_EventObject.DiscardUnknown(m)
}

var xxx_messageInfo_EventObject proto.InternalMessageInfo

func (m *EventObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventObject) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EventObject) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *EventObject) GetState() EventObject_State {
	if m != nil {
		return m.State
	}
	return EventObject_NEW
}

func (m *EventObject) GetAssignee() string {
	if m != nil {
		return m.Assignee
	}
	return ""
}

func (m *EventObject) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EventObject) GetSeverity() EventObject_Severity {
	if m != nil {
		return m.Severity
	}
	return EventObject_INFO
}

func (m *EventObject) GetLabel() []string {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *EventObject) GetActivity() []*Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

type EventRef struct {
	// The id of the EventObject to get
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRef) Reset()         { *m = EventRef{} }
func (m *EventRef) String() string { return proto.CompactTextString(m) }
func (*EventRef) ProtoMessage()    {}
func (*EventRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb09a02427acf6d9, []int{1}
}

func (m *EventRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRef.Unmarshal(m, b)
}
func (m *EventRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRef.Marshal(b, m, deterministic)
}
func (m *EventRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRef.Merge(m, src)
}
func (m *EventRef) XXX_Size() int {
	return xxx_messageInfo_EventRef.Size(m)
}
func (m *EventRef) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRef.DiscardUnknown(m)
}

var xxx_messageInfo_EventRef proto.InternalMessageInfo

func (m *EventRef) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Activity struct {
	ModifiedBy           string               `protobuf:"bytes,1,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	ModifiedTime         *timestamp.Timestamp `protobuf:"bytes,2,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	Description          []*Activity_Change   `protobuf:"bytes,3,rep,name=description,proto3" json:"description,omitempty"`
	Comment              string               `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb09a02427acf6d9, []int{2}
}

func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (m *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(m, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetModifiedBy() string {
	if m != nil {
		return m.ModifiedBy
	}
	return ""
}

func (m *Activity) GetModifiedTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTime
	}
	return nil
}

func (m *Activity) GetDescription() []*Activity_Change {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Activity) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Activity_Change struct {
	Type                 Activity_ChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=veidemann.api.eventhandler.v1.Activity_ChangeType" json:"type,omitempty"`
	Field                string              `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	OldVal               string              `protobuf:"bytes,3,opt,name=old_val,json=oldVal,proto3" json:"old_val,omitempty"`
	NewVal               string              `protobuf:"bytes,4,opt,name=new_val,json=newVal,proto3" json:"new_val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Activity_Change) Reset()         { *m = Activity_Change{} }
func (m *Activity_Change) String() string { return proto.CompactTextString(m) }
func (*Activity_Change) ProtoMessage()    {}
func (*Activity_Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb09a02427acf6d9, []int{2, 0}
}

func (m *Activity_Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity_Change.Unmarshal(m, b)
}
func (m *Activity_Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity_Change.Marshal(b, m, deterministic)
}
func (m *Activity_Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity_Change.Merge(m, src)
}
func (m *Activity_Change) XXX_Size() int {
	return xxx_messageInfo_Activity_Change.Size(m)
}
func (m *Activity_Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Activity_Change proto.InternalMessageInfo

func (m *Activity_Change) GetType() Activity_ChangeType {
	if m != nil {
		return m.Type
	}
	return Activity_CREATED
}

func (m *Activity_Change) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Activity_Change) GetOldVal() string {
	if m != nil {
		return m.OldVal
	}
	return ""
}

func (m *Activity_Change) GetNewVal() string {
	if m != nil {
		return m.NewVal
	}
	return ""
}

type Data struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb09a02427acf6d9, []int{3}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Data) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("veidemann.api.eventhandler.v1.EventObject_State", EventObject_State_name, EventObject_State_value)
	proto.RegisterEnum("veidemann.api.eventhandler.v1.EventObject_Severity", EventObject_Severity_name, EventObject_Severity_value)
	proto.RegisterEnum("veidemann.api.eventhandler.v1.Activity_ChangeType", Activity_ChangeType_name, Activity_ChangeType_value)
	proto.RegisterType((*EventObject)(nil), "veidemann.api.eventhandler.v1.EventObject")
	proto.RegisterType((*EventRef)(nil), "veidemann.api.eventhandler.v1.EventRef")
	proto.RegisterType((*Activity)(nil), "veidemann.api.eventhandler.v1.Activity")
	proto.RegisterType((*Activity_Change)(nil), "veidemann.api.eventhandler.v1.Activity.Change")
	proto.RegisterType((*Data)(nil), "veidemann.api.eventhandler.v1.Data")
}

func init() { proto.RegisterFile("eventhandler/v1/resources.proto", fileDescriptor_bb09a02427acf6d9) }

var fileDescriptor_bb09a02427acf6d9 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0x71, 0x7e, 0x9c, 0x9b, 0x0f, 0xe4, 0x6f, 0xc4, 0xf7, 0xd5, 0x8a, 0x54, 0x11, 0xa5,
	0x52, 0x49, 0x17, 0x4c, 0x4a, 0x58, 0x74, 0x51, 0xa9, 0x95, 0x89, 0x4d, 0x69, 0x85, 0x12, 0x34,
	0x50, 0x50, 0xbb, 0x89, 0xc6, 0xf1, 0x24, 0x4c, 0x6b, 0x8f, 0xad, 0x78, 0x62, 0x94, 0x6d, 0x9f,
	0xa2, 0x6f, 0xd3, 0xa7, 0xe9, 0x7b, 0x54, 0x1e, 0xdb, 0x21, 0x62, 0x01, 0x65, 0xe7, 0x73, 0x7d,
	0xce, 0xbd, 0xc7, 0x77, 0xce, 0x18, 0xf6, 0x58, 0xca, 0x84, 0xbc, 0xa1, 0xc2, 0x0f, 0xd8, 0xa2,
	0x9f, 0x1e, 0xf6, 0x17, 0x2c, 0x89, 0x96, 0x8b, 0x29, 0x4b, 0x70, 0xbc, 0x88, 0x64, 0x84, 0x9e,
	0xa7, 0x8c, 0xfb, 0x2c, 0xa4, 0x42, 0x60, 0x1a, 0x73, 0xbc, 0x49, 0xc7, 0xe9, 0x61, 0x7b, 0x6f,
	0x1e, 0x45, 0xf3, 0x80, 0xf5, 0x15, 0xd9, 0x5b, 0xce, 0xfa, 0x92, 0x87, 0x2c, 0x91, 0x34, 0x8c,
	0x73, 0x7d, 0xf7, 0xb7, 0x0e, 0x2d, 0x37, 0x13, 0x8d, 0xbd, 0x6f, 0x6c, 0x2a, 0xd1, 0x0e, 0x54,
	0xb8, 0x6f, 0x69, 0x1d, 0xad, 0xd7, 0x24, 0x15, 0xee, 0x23, 0x04, 0x55, 0xb9, 0x8a, 0x99, 0x55,
	0x51, 0x15, 0xf5, 0x8c, 0xfe, 0x87, 0x7a, 0x6e, 0xc2, 0xd2, 0x55, 0xb5, 0x40, 0xe8, 0x04, 0x6a,
	0x89, 0xa4, 0x92, 0x59, 0xd5, 0x8e, 0xd6, 0xdb, 0x19, 0xbc, 0xc6, 0x0f, 0x7a, 0xc3, 0x1b, 0x63,
	0xf1, 0x45, 0xa6, 0x23, 0xb9, 0x1c, 0xb5, 0xc1, 0xa0, 0x49, 0xc2, 0xe7, 0x82, 0x31, 0xab, 0xa6,
	0x26, 0xac, 0x31, 0x7a, 0x03, 0x55, 0x9f, 0x4a, 0x6a, 0xd5, 0x3b, 0x7a, 0xaf, 0x35, 0x78, 0xf1,
	0xc8, 0x08, 0x87, 0x4a, 0x4a, 0x94, 0x00, 0x8d, 0xc1, 0x48, 0x58, 0xca, 0x16, 0x5c, 0xae, 0xac,
	0x86, 0xf2, 0x77, 0xf4, 0x14, 0x7f, 0x85, 0x94, 0xac, 0x9b, 0xa0, 0x5d, 0xa8, 0x05, 0xd4, 0x63,
	0x81, 0x65, 0x74, 0xf4, 0x5e, 0x93, 0xe4, 0x00, 0x0d, 0xc1, 0xa0, 0x53, 0xc9, 0xd3, 0x6c, 0x4c,
	0x53, 0x79, 0xdc, 0x7f, 0x64, 0x8c, 0x5d, 0xd0, 0xc9, 0x5a, 0xd8, 0x7d, 0x09, 0x35, 0xb5, 0x10,
	0xd4, 0x00, 0x7d, 0xe4, 0x5e, 0x9b, 0x5b, 0xc8, 0x80, 0xea, 0xf8, 0xdc, 0x1d, 0x99, 0x1a, 0x02,
	0xa8, 0x0f, 0xcf, 0xc6, 0x17, 0xae, 0x63, 0x56, 0xba, 0xaf, 0xc0, 0x28, 0x8d, 0x65, 0x8c, 0x8f,
	0xa3, 0x93, 0x71, 0xce, 0xbd, 0xb6, 0x49, 0xc6, 0x6d, 0x42, 0xcd, 0x25, 0x64, 0x4c, 0xcc, 0x4a,
	0xb7, 0x0d, 0x86, 0xfa, 0x1e, 0xc2, 0x66, 0xf7, 0xcf, 0xb8, 0xfb, 0x4b, 0x07, 0xa3, 0x74, 0x81,
	0xf6, 0xa0, 0x15, 0x46, 0x3e, 0x9f, 0x71, 0xe6, 0x4f, 0xbc, 0x55, 0xc1, 0x82, 0xb2, 0x74, 0xbc,
	0x42, 0xef, 0x61, 0x7b, 0x4d, 0xc8, 0xd2, 0xa4, 0xa2, 0xd1, 0x1a, 0xb4, 0x71, 0x1e, 0x35, 0x5c,
	0x46, 0x0d, 0x5f, 0x96, 0x51, 0x23, 0xff, 0x94, 0x82, 0xac, 0x84, 0xce, 0xa1, 0xe5, 0xb3, 0x64,
	0xba, 0xe0, 0xb1, 0xe4, 0x91, 0xb0, 0x74, 0xb5, 0x25, 0xfc, 0x97, 0x5b, 0xc2, 0xc3, 0x1b, 0x2a,
	0xe6, 0x8c, 0x6c, 0xb6, 0x40, 0x16, 0x34, 0xa6, 0x51, 0x18, 0x32, 0x21, 0x55, 0xf4, 0x9a, 0xa4,
	0x84, 0xed, 0x9f, 0x1a, 0xd4, 0x73, 0x05, 0x3a, 0x29, 0x92, 0xac, 0xa9, 0xc3, 0x1f, 0x3c, 0x6d,
	0xde, 0xe5, 0x2a, 0x66, 0x45, 0xfa, 0x77, 0xa1, 0x36, 0xe3, 0x2c, 0xf0, 0x8b, 0x2b, 0x91, 0x03,
	0xf4, 0x0c, 0x1a, 0x51, 0xe0, 0x4f, 0x52, 0x1a, 0x94, 0x97, 0x22, 0x0a, 0xfc, 0x2b, 0x1a, 0x64,
	0x2f, 0x04, 0xbb, 0x55, 0x2f, 0x72, 0x6f, 0x75, 0xc1, 0x6e, 0xaf, 0x68, 0xd0, 0xfd, 0x04, 0x70,
	0xd7, 0x1b, 0xb5, 0xa0, 0x31, 0x24, 0xae, 0x7d, 0xe9, 0x3a, 0xe6, 0x16, 0xfa, 0x17, 0xb6, 0xaf,
	0xec, 0xb3, 0xcf, 0xee, 0x64, 0x78, 0x6a, 0x8f, 0x3e, 0xb8, 0x8e, 0xa9, 0xa1, 0x6d, 0x68, 0xda,
	0x84, 0xd8, 0x5f, 0x26, 0xb6, 0xe3, 0x98, 0x95, 0x3b, 0xe8, 0xb8, 0x67, 0xa6, 0xde, 0xc5, 0x50,
	0xcd, 0xa2, 0x8e, 0x4c, 0xd0, 0xbf, 0xb3, 0xf2, 0xd0, 0xb2, 0xc7, 0xcc, 0x6d, 0x4a, 0x83, 0x65,
	0x79, 0x81, 0x73, 0x70, 0xfc, 0x43, 0x83, 0x7d, 0x11, 0x61, 0xe1, 0x61, 0x21, 0xe8, 0xc3, 0x9b,
	0x38, 0xfe, 0x4f, 0xe5, 0xe6, 0x34, 0x2f, 0x90, 0xf2, 0xf7, 0x73, 0xae, 0x7d, 0x7d, 0x37, 0xe7,
	0xf2, 0x66, 0xe9, 0xe1, 0x69, 0x14, 0xf6, 0x45, 0x20, 0x6e, 0x69, 0x7f, 0xdd, 0xe8, 0x80, 0xc6,
	0xfc, 0x60, 0x1e, 0xf5, 0xef, 0xfd, 0xbd, 0xde, 0x6e, 0x62, 0xaf, 0xae, 0x92, 0x72, 0xf4, 0x27,
	0x00, 0x00, 0xff, 0xff, 0xc4, 0x3e, 0xfe, 0x4c, 0xe4, 0x04, 0x00, 0x00,
}
